POST http://localhost:8080/todos
Content-Type: application/json

{
    "title":"laundry",
    "completed":true
}
###
GET http://localhost:8080/todos

###
GET http://localhost:8080/todos/0

###
PATCH  http://localhost:8080/todos/617fe0bf981c437a1027eac8
Content-Type: application/json

{
    "title":"shower",
    "completed":false
}
###
DELETE http://localhost:8080/todos/617fe0c1981c437a1027eacc
###
